### ISSUE TITLE
pygs in pyqt

### ISSUE THREAD

**Issue by LeunamBk** [Asvel/pygs#1]
HI, first off all, thank you for bringing cross-platform global shortcuts to python!!! 
Could you please provide an example of how to include the hotkey functionality in a pyqt app?

yours sincerely Mrs. Frisbee

**Comment by Asvel** [comment]
There is an example in [examples/simple.py](https://github.com/Asvel/pygs/blob/master/examples/simple.py).

Generally speaking, you can enable a global hotkey by:
- Make sure there is a [QApplication](http://qt-project.org/doc/qt-5/qapplication.html) instance exists
- Create an instance of pygs.[QxtGlobalShortcut](http://libqxt.bitbucket.org/doc/tip/qxtglobalshortcut.html)
- Set the hotkey through [setShortcut](http://libqxt.bitbucket.org/doc/tip/qxtglobalshortcut.html#setShortcut), it requires a [QKeySequence](http://qt-project.org/doc/qt-5/qkeysequence.html)
- Connect the signal [activated](http://libqxt.bitbucket.org/doc/tip/qxtglobalshortcut.html#activated) to some slots
