### ISSUE TITLE
setup.py fails on Python 2.x

### ISSUE THREAD

**Issue by Aculeo** [Asvel/pygs#2]
When trying to install pygs with pip it fails with the following error:

```
File "/tmp/pip_build_root/PyGlobalShortcut/setup.py", line 30, in check_call
except FileNotFoundError as ex:
NameError: global name 'FileNotFoundError' is not defined
```

`FileNotFoundError` does not exist in Python 2.x

**Comment by Asvel** [comment]
Fix it, but in this case it will keep on throwing a real exception about file not found
